### ISSUE TITLE
Deprecated function - cannot start integration

### ISSUE THREAD

**Issue by haasstee** [RobHofmann/HomeAssistant-GreeClimateComponent#379]
![Image](https://github.com/user-attachments/assets/2290320d-9646-4afe-848d-fe693e3d9c8e)

I got following error - and integration cannot start

2025-10-03 11:13:19.712 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'gree' sets option flow config_entry explicitly, which is deprecated at custom_components/gree/config_flow.py, line 239: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'gree' custom integration
2025-10-03 11:13:51.628 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Gree Climate for gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gree/__init__.py", line 105, in async_setup_entry
    device = await create_gree_device(hass, combined_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gree/climate.py", line 71, in create_gree_device
    mac_addr = config.get(CONF_MAC).encode().replace(b":", b"")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by RobHofmann** [comment]
I'm currently on the latest Home Assistant (2025.10.1) and the latest version of this custom component (3.3.1). No issues here.

I got my logging on error, so not sure about the warning, but that should not keep it from booting.

Make sure your versions are up-to-date.
